<?xml version="1.0" encoding="utf-8"?><Database Name="EasyRouteDB" Class="EasyRouteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Contato" Member="Contato">
    <Type Name="Contato">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Telefone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Cpf" Type="System.String" DbType="VarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Contato_Endereco" Member="Endereco" ThisKey="Id" OtherKey="ContatoId" Type="Endereco" />
    </Type>
  </Table>
  <Table Name="dbo.Endereco" Member="Endereco">
    <Type Name="Endereco">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Logradouro" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Numero" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="Bairro" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Complemento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cep" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Cidade" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ContatoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Contato_Endereco" Member="Contato" ThisKey="ContatoId" OtherKey="Id" Type="Contato" IsForeignKey="true" />
    </Type>
  </Table>
</Database>