USE EasyRouteDB
GO

CREATE TABLE Contato(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(255) NOT NULL,
	Telefone VARCHAR(15) NOT NULL,
	Cpf VARCHAR(14) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	Status BIT NOT NULL
)

CREATE TABLE Endereco(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Logradouro VARCHAR(255) NOT NULL,
	Numero VARCHAR(6) NOT NULL,
	Bairro VARCHAR(60) NOT NULL,
	Complemento VARCHAR(100) NULL,
	Cep VARCHAR(9) NOT NULL,
	Cidade VARCHAR(60) NOT NULL,
	Estado VARCHAR(2) NOT NULL,
	Status BIT NOT NULL,
	ContatoId INT NOT NULL,
	FOREIGN KEY (ContatoId) REFERENCES Contato(Id)
)